load 'board.rb'
load 'display.rb'
load 'piece.rb'
load 'player.rb'
load 'game.rb'
load 'pieces/movement_patterns/stepping.rb'
load 'pieces/movement_patterns/sliding.rb'
load 'pieces/bishop.rb'
load 'pieces/king.rb'
load 'pieces/queen.rb'
load 'pieces/knight.rb'
load 'pieces/null_piece.rb'
load 'pieces/rook.rb'
load 'pieces/pawn.rb'

